---
title: "R VS Python in string"
author: "Zhang JIan"
date: "2020/4/5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### R和Python处理字符串的代码，你更喜欢哪种？

#### 先看R的
```{r}
library(stringr)
highlighted_poems <- "Afterimages:Audre Lorde:1997,  The Shadow:William Carlos Williams:1915, Ecstasy:Gabriela Mistral:1925,   Georgia Dusk:Jean Toomer:1923,   Parting Before Daybreak:An Qi:2014, The Untold Want:Walt Whitman:1871, Mr. Grumpledump's Song:Shel Silverstein:2004, Angel Sound Mexico City:Carmen Boullosa:2013, In Love:Kamala Suraiyya:1965, Dream Variations:Langston Hughes:1994, Dreamwood:Adrienne Rich:1987"

highlighted_poems_list <-str_split(highlighted_poems , pattern = ",")
highlighted_poems_stripped <- c()
for (i in highlighted_poems_list[[1]] ){
  k = str_trim(i)
  highlighted_poems_stripped = append(highlighted_poems_stripped,k)
}

highlighted_poems_details = c()
# 切分冒号
for (i in highlighted_poems_stripped ){
  k = str_split(i,pattern = ":")
  highlighted_poems_details = append(highlighted_poems_details,k)
}

titles <- c()
poets <- c()
dates <- c()
for (i in highlighted_poems_details){
  
  titles = append(titles,i[1])
  poets = append(titles,i[2])
  dates = append(dates,i[3])
}

for ( i in seq(1,length(titles))){
  print(paste("The poem ",titles[i]," was published by ",poets[i]," in ",dates[i],"."))
  
}
```

### 下面开始是Python的代码

```{python}
highlighted_poems = "Afterimages:Audre Lorde:1997,  The Shadow:William Carlos Williams:1915, Ecstasy:Gabriela Mistral:1925,   Georgia Dusk:Jean Toomer:1923,   Parting Before Daybreak:An Qi:2014, The Untold Want:Walt Whitman:1871, Mr. Grumpledump's Song:Shel Silverstein:2004, Angel Sound Mexico City:Carmen Boullosa:2013, In Love:Kamala Suraiyya:1965, Dream Variations:Langston Hughes:1994, Dreamwood:Adrienne Rich:1987"

highlighted_poems_list = highlighted_poems.split(',')

highlighted_poems_stripped = []
for i in highlighted_poems_list:
  highlighted_poems_stripped.append(i.strip())

highlighted_poems_details = []

for i in highlighted_poems_stripped:
  highlighted_poems_details.append(i.split(':'))
  
titles =[]
poets = []
dates = []

for i in highlighted_poems_details:
  titles.append(i[0])
  poets.append(i[1])
  dates.append(i[2])

for i in range(len(titles)):
  res = 'The poem {tit} was published by {poet} in {Date}.'.format(tit=titles[i],poet=poets[i],Date=dates[i])
  print(res)
```

