---
title: 时间序列分析1
author: 张剑
date: '2020-03-21'
slug: 时间序列分析1
categories:
  - 项目评估
tags:
  - R
  - Forecast
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### 时间序列最简单的预测方法
#### 均值法
$$\hat{y}_{T+h | T}=\left(y_{1}+\cdots+y_{T}\right) / T$$

## 一个例子
```{r}
library(tidyverse)
library(forecast)
library(fpp2)
library(ggfortify)
library(ggthemes)
library(timetk)
library(DT)
# 设定数据
beer2 <- window(ausbeer,start=1992,end=c(2007,4))
# 均值预测
k<-meanf(beer2,h=11)
k$mean

beer2_f <- ts.union(beer2,k$mean)
colnames(beer2_f) <- c("原始值",'均值预测')
autoplot(beer2_f,size=1.4,alpha=0.7)+theme_clean()+ggtitle("啤酒销量均值预测")+
  xlab("年份")

#naive预测
n <- naive(beer2,h=11)
n$mean
beer2_f <- ts.union(beer2,k$mean,n$mean)
colnames(beer2_f) <- c("原始值",'均值预测','naive预测')
autoplot(beer2_f,size=1.4,alpha=0.7)+theme_clean()+ggtitle("啤酒销量均值预测")+
  xlab("年份")

#snaive预测
s_n <- snaive(beer2,h=11)
s_n$mean
beer2_f <- ts.union(beer2,k$mean,n$mean,s_n$mean)
colnames(beer2_f) <- c("原始值",'均值预测','naive预测','snaive预测')
autoplot(beer2_f,size=1.4,alpha=0.7)+theme_clean()+ggtitle("啤酒销量均值预测")+
  xlab("年份")
#漂移法
d<- rwf(beer2,h=11,drift = T)
d$mean
beer2_f <- ts.union(beer2,k$mean,n$mean,s_n$mean,d$mean)
colnames(beer2_f) <- c("原始值",'均值预测','naive预测','snaive预测','漂移法')
autoplot(beer2_f,size=1.4,alpha=0.7)+theme_clean()+ggtitle("啤酒销量均值预测")+
  xlab("年份")
```

## 预测精度的例子
```{r}
beer2 <- window(ausbeer,start=1992,end=c(2007,4))
beerfit1 <- meanf(beer2,h=10)
beerfit2 <- rwf(beer2,h=10)
beerfit3 <- snaive(beer2,h=10)
beer3 <- window(ausbeer, start=2008)
accuracy(beerfit1, beer3)
accuracy(beerfit2, beer3)
accuracy(beerfit3, beer3)
```
```{r message=FALSE, warning=FALSE}
#这里我们直接使用autoplayer包
googfc1 <- meanf(goog200, h=40)
googfc2 <- rwf(goog200, h=40)
googfc3 <- rwf(goog200, drift=TRUE, h=40)
autoplot(subset(goog, end = 240)) +
  autolayer(googfc1, PI=FALSE, series="均值") +
  autolayer(googfc2, PI=F, series="Naïve") +
  autolayer(googfc3, PI=FALSE, series="漂移") +
  xlab("天") + ylab("收盘价（美元）") +
  ggtitle("谷歌公司每日股价（截止至2013年12月6日）") +
  guides(colour=guide_legend(title="预测"))+
  theme(text = element_text(family = "STHeiti"))+
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme_clean()

#计算预测精度
googtest <- window(goog, start=201, end=240)
accuracy(googfc1, googtest)
accuracy(googfc2, googtest)
accuracy(googfc3, googtest)
```

### 移动平均，简单移动平均的阶数常常是奇数阶，在阶数为m=2k+1的移动平均中，中心值两侧各有k个观测值可以被平均
### 先看一个白噪声的例子
```{r}
set.seed(3)
wn <- ts(rnorm(36))
autoplot(wn,size =1.1,alpha = 0.7)+theme_clean()
autoplot(mstl(wn))+theme_clean()
```



```{r warning=FALSE}
data(elecsales) 
ele <- timetk::tk_tbl(elecsales)

ele <- ele %>%
  mutate(mm = ma(elecsales,order = 5))
ele %>% datatable(colnames = c("年份","原始数据","MA5"))

#ma5第一个数是2381.53，具体计算方式如下：
paste("这个数是这样得到的：",mean(pull(ele[1:5,'value'])),"下面会显示一个TRUE")
ele[3,3]==mean(pull(ele[1:5,'value']))

#ma5图
autoplot(elecsales,size=1.5,alpha=0.6 ,series="原始数据") +
  autolayer(ma(elecsales,5), series="5-MA",size=1.5,alpha=0.6) +
  xlab("年份") + ylab("亿瓦时") +
  ggtitle("年度住宅售电量") +
  scale_colour_manual(values=c("Data"="grey50","5-MA"="red"),
                     breaks=c("Data","5-MA"))+
  theme(text = element_text(family = "STHeiti"))+
  theme(plot.title = element_text(hjust = 0.5))+theme_clean()


#ma3图
autoplot(elecsales,size=1.5,alpha=0.6 ,series="原始数据") +
  autolayer(ma(elecsales,3), series="3-MA",size=1.5,alpha=0.6) +
  xlab("年份") + ylab("亿瓦时") +
  ggtitle("年度住宅售电量") +
  scale_colour_manual(values=c("Data"="grey50","3-MA"="red"),
                     breaks=c("Data","3-MA"))+
  theme(text = element_text(family = "STHeiti"))+
  theme(plot.title = element_text(hjust = 0.5))+theme_clean()

#ma3图
autoplot(elecsales,size=1.5,alpha=0.6 ,series="原始数据") +
  autolayer(ma(elecsales,7), series="7-MA",size=1.5,alpha=0.6) +
  xlab("年份") + ylab("亿瓦时") +
  ggtitle("年度住宅售电量") +
  scale_colour_manual(values=c("Data"="grey50","7-MA"="red"),
                     breaks=c("Data","7-MA"))+
  theme(text = element_text(family = "STHeiti"))+
  theme(plot.title = element_text(hjust = 0.5))+theme_clean()
```
## 移动平均的移动平均

```{r}

beer2 <- window(ausbeer,start=1992) 
beer2_df <- timetk::tk_tbl(beer2)

beer2_df <- beer2_df %>%
  mutate(mm = ma(beer2,order = 4,centre = F)) %>%
  mutate(mmm = ma(beer2,order = 4,centre = T))
beer2_df %>% datatable(colnames = c("年份","原始数据","MA4","2*4MA"))
# 450 = (451.25+448.75）/2
```

## 使用线性模型对时间序列进行预测
$$y_{t}=\beta_{0}+\beta_{1} t+\beta_{2} d_{2, t}+\beta_{3} d_{3, t}+\beta_{4} d_{4, t}+\varepsilon_{t}$$
```{r warning=FALSE}
beer2 <- window(ausbeer, start=1992)
fit.beer <- tslm(beer2 ~ trend + season)
summary(fit.beer)
#拟合完了
#画图

beer2_f <- ts.union(beer2,fitted(fit.beer))
colnames(beer2_f) <- c("原始值",'拟合值')

autoplot(beer2_f, series="真实值",size=1,alpha=0.8) +
  xlab("年份") + ylab("万升") +
  ggtitle("啤酒的季度产出")+
  theme(text = element_text(family = "STHeiti"))+
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_clean()

cbind(Data=beer2, Fitted=fitted(fit.beer)) %>%
  as.data.frame() %>%
  ggplot(aes(x=Data, y=Fitted, colour=as.factor(cycle(beer2)))) +
    geom_point() +
    ylab("拟合值") + xlab("真实值") +
    ggtitle("啤酒的季度产出") +
    scale_colour_brewer(palette="Dark2", name="季度") +
    geom_abline(intercept=0, slope=1)+
    theme(text = element_text(family = "STHeiti"))+
    theme(plot.title = element_text(hjust = 0.5))
```

### 使用拟合好的模型进行预测
```{r warning=FALSE}
beer2 <- window(ausbeer, start=1992)
ggAcf(beer2)
fit.beer <- tslm(beer2 ~ trend + season)
fcast <- forecast(fit.beer)
summary(fcast)
autoplot(fcast) +
  ggtitle("利用线性回归模型预测啤酒产出")+
  theme(text = element_text(family = "STHeiti"))+
  theme(plot.title = element_text(hjust = 0.5)) + theme_clean()
```
```{r}
autoplot(marathon,size=1.1,alpha = 0.5,ts.colour = "dodgerblue3")+theme_clean()+
  ggtitle("马拉松数据")+
  xlab("年份")+
  ylab("跑完用时")
#异方差现象
```

```{r}
library(forecast)

h <- 4 # 预测四期
fit.lin <- tslm(marathon ~ trend )
fcasts.lin <- forecast(fit.lin, h = h)
fit.exp <- tslm(marathon ~ trend , lambda = 0)
fcasts.exp <- forecast(fit.exp, h = h)

marathon_f <- ts.union(marathon,fitted(fit.lin),fitted(fit.exp))
colnames(marathon_f) <- c("原始值",'线性拟合值','非线性拟合值')

autoplot(marathon_f,size=1.1,alpha=0.5) +
  ggtitle("利用线性回归模型预测啤酒产出")+
  theme(text = element_text(family = "STHeiti"))+
  theme(plot.title = element_text(hjust = 0.5)) + theme_clean()+
  autolayer(fcasts.lin, series =   '线性预测')+
  autolayer(fcasts.exp,series =  '非线性预测') +xlab('年份')+ylab('跑完时间')+
  ggtitle("马拉松数据")
```




